// Static synthetic LIHTC property dataset for the Discover stretch page.
// Source: HUD LIHTC Database subset for the Boston-Cambridge-Newton MSA.
// Public location data only — no landlord-revenue signals, no demographic
// features, no acceptance predictions, no ranking by any protected trait.
// Availability is ALWAYS "unknown" unless separately supplied by the property.

export type Property = {
  id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  total_units: number;
  low_income_units: number;
  bedroom_mix: string;
  year_placed_in_service: number | null;
  availability: "unknown"; // by design — never predicted
  source: string;
  source_url: string;
};

export const PROPERTIES: Property[] = [
  {
    id: "MAB20200006",
    name: "Burbank Apts",
    address: "31 Burbank Street",
    city: "Boston",
    state: "MA",
    zip: "02115",
    total_units: 52,
    low_income_units: 39,
    bedroom_mix: "Studio/1BR/2BR",
    year_placed_in_service: 2020,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20120035",
    name: "Castle Square Ii",
    address: "494 Tremont St",
    city: "Boston",
    state: "MA",
    zip: "02116",
    total_units: 500,
    low_income_units: 500,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2012,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB00000253",
    name: "Dartmouth Tcb",
    address: "792 Tremont St",
    city: "Boston",
    state: "MA",
    zip: "02118",
    total_units: 83,
    low_income_units: 83,
    bedroom_mix: "Studio/1BR/2BR/3BR/4BR",
    year_placed_in_service: null,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20080050",
    name: "Dudley Village South",
    address: "571 Dudley St",
    city: "Boston",
    state: "MA",
    zip: "02125",
    total_units: 26,
    low_income_units: 26,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2008,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20151006",
    name: "Georgetown Homes Phase One",
    address: "11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41 Georgetown Drive",
    city: "Boston",
    state: "MA",
    zip: "01570",
    total_units: 0,
    low_income_units: 0,
    bedroom_mix: "unknown",
    year_placed_in_service: 2015,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAA19950005",
    name: "Heritage At Cleveland Circle",
    address: "50 Sutherland Rd",
    city: "Boston",
    state: "MA",
    zip: "02135",
    total_units: 90,
    low_income_units: 18,
    bedroom_mix: "Studio/1BR",
    year_placed_in_service: 1995,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20110110",
    name: "Jamaica Plain Apts",
    address: "48 School St",
    city: "Boston",
    state: "MA",
    zip: "02108",
    total_units: 103,
    low_income_units: 103,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2011,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB19940100",
    name: "Project Home",
    address: "1688 Washington St",
    city: "Boston",
    state: "MA",
    zip: "02118",
    total_units: 3,
    low_income_units: 3,
    bedroom_mix: "unknown",
    year_placed_in_service: 1994,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20040065",
    name: "Robert L Fortes House",
    address: "541 Shawmut Ave",
    city: "Boston",
    state: "MA",
    zip: "02118",
    total_units: 44,
    low_income_units: 44,
    bedroom_mix: "1BR",
    year_placed_in_service: 2004,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20040070",
    name: "Roxbury Tenants",
    address: "44 Francis St",
    city: "Boston",
    state: "MA",
    zip: "02115",
    total_units: 20,
    low_income_units: 13,
    bedroom_mix: "2BR/3BR",
    year_placed_in_service: 2004,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20191007",
    name: "The Clarion",
    address: "295-311 Blue Hill Avenue",
    city: "Boston",
    state: "MA",
    zip: "02121",
    total_units: 63,
    low_income_units: 61,
    bedroom_mix: "2BR/3BR/4BR",
    year_placed_in_service: 2019,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20040075",
    name: "The Metropolitan",
    address: "1 Nassau St",
    city: "Boston",
    state: "MA",
    zip: "02111",
    total_units: 81,
    low_income_units: 81,
    bedroom_mix: "Studio/1BR/2BR/3BR",
    year_placed_in_service: 2004,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20172003",
    name: "Wayne At Bicknell",
    address: "92-94 Esmond Street",
    city: "Boston",
    state: "MA",
    zip: "02121",
    total_units: 72,
    low_income_units: 72,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2017,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20171012",
    name: "Whittier Place",
    address: "60 Southern Avenue",
    city: "Boston",
    state: "MA",
    zip: "02124",
    total_units: 44,
    low_income_units: 44,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2017,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20161001",
    name: "51-57 Beals Street",
    address: "55-57 Beals Street",
    city: "Brookline",
    state: "MA",
    zip: "02446",
    total_units: 31,
    low_income_units: 31,
    bedroom_mix: "Studio",
    year_placed_in_service: 2016,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAC00000005",
    name: "51-57 Beals Street",
    address: "57 Beals St",
    city: "Brookline",
    state: "MA",
    zip: "02446",
    total_units: 31,
    low_income_units: 0,
    bedroom_mix: "unknown",
    year_placed_in_service: null,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20150003",
    name: "Bishop Allen Apartments",
    address: "70 + 77 Bishop Allen Drive; 51 + 62 Norfolk Street",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    total_units: 32,
    low_income_units: 32,
    bedroom_mix: "2BR/3BR",
    year_placed_in_service: 2015,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20030025",
    name: "Cambridge Alliance",
    address: "55 Columbia St",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    total_units: 42,
    low_income_units: 37,
    bedroom_mix: "1BR/2BR/3BR/4BR",
    year_placed_in_service: 2003,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20050055",
    name: "Lancaster Street Apts",
    address: "8 Lancaster St",
    city: "Cambridge",
    state: "MA",
    zip: "02140",
    total_units: 65,
    low_income_units: 55,
    bedroom_mix: "Studio/1BR/2BR",
    year_placed_in_service: 2005,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20160003",
    name: "Temple Place",
    address: "5 Temple Street",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    total_units: 41,
    low_income_units: 41,
    bedroom_mix: "1BR/2BR",
    year_placed_in_service: 2016,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB00000307",
    name: "Harborcov Community Housing",
    address: "63 Washington Ave",
    city: "Chelsea",
    state: "MA",
    zip: "02150",
    total_units: 24,
    low_income_units: 24,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: null,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20130011",
    name: "Highland Terrace",
    address: "47 Gerrish Ave",
    city: "Chelsea",
    state: "MA",
    zip: "02150",
    total_units: 32,
    low_income_units: 0,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: 2013,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20080100",
    name: "Till Building",
    address: "241 Broadway",
    city: "Chelsea",
    state: "MA",
    zip: "02150",
    total_units: 23,
    low_income_units: 23,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: 2008,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20080080",
    name: "Parkway Heights",
    address: "201 Chelsea St",
    city: "Everett",
    state: "MA",
    zip: "02149",
    total_units: 74,
    low_income_units: 47,
    bedroom_mix: "1BR/2BR",
    year_placed_in_service: 2008,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB19920045",
    name: "Whitney-Lorenti House",
    address: "15 Summer St",
    city: "Everett",
    state: "MA",
    zip: "02149",
    total_units: 50,
    low_income_units: 50,
    bedroom_mix: "1BR/2BR",
    year_placed_in_service: 1992,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20050035",
    name: "Cross Street Housing",
    address: "354 Cross St",
    city: "Malden",
    state: "MA",
    zip: "02148",
    total_units: 19,
    low_income_units: 0,
    bedroom_mix: "2BR/3BR/4BR",
    year_placed_in_service: 2005,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20120060",
    name: "Heritage 195 Pleasant St",
    address: "195 Pleasant St",
    city: "Malden",
    state: "MA",
    zip: "02148",
    total_units: 176,
    low_income_units: 156,
    bedroom_mix: "Studio/1BR",
    year_placed_in_service: 2012,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB19910040",
    name: "Kendrigan Place",
    address: "10 Winter St",
    city: "Quincy",
    state: "MA",
    zip: "02169",
    total_units: 78,
    low_income_units: 64,
    bedroom_mix: "1BR/2BR",
    year_placed_in_service: 1991,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20120115",
    name: "Winter Gardens Apts",
    address: "45 Winter St",
    city: "Quincy",
    state: "MA",
    zip: "02169",
    total_units: 24,
    low_income_units: 24,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: 2012,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB00000055",
    name: "33 Bow St",
    address: "33 Bow St",
    city: "Somerville",
    state: "MA",
    zip: "02143",
    total_units: 18,
    low_income_units: 16,
    bedroom_mix: "2BR/3BR/4BR",
    year_placed_in_service: null,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20090060",
    name: "St Polycarp I",
    address: "460 Mystic Ave",
    city: "Somerville",
    state: "MA",
    zip: "02145",
    total_units: 24,
    low_income_units: 24,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: 2009,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
  {
    id: "MAB20140014",
    name: "St Polycarp Iii",
    address: "5 Memorial Rd",
    city: "Somerville",
    state: "MA",
    zip: "02145",
    total_units: 31,
    low_income_units: 31,
    bedroom_mix: "1BR/2BR/3BR",
    year_placed_in_service: 2014,
    availability: "unknown",
    source: "HUD LIHTC Database (Boston-Cambridge-Newton MSA subset)",
    source_url: "https://lihtc.huduser.gov/",
  },
];

// Every feature we surface + why. No hidden proxies.
export const PROPERTY_FEATURES: Array<{ field: keyof Property; purpose: string }> = [
  { field: "name", purpose: "Project name — public HUD LIHTC field." },
  { field: "address", purpose: "Street address — public location data." },
  { field: "city", purpose: "City — matches the Boston-Cambridge-Newton MSA MTSP row." },
  { field: "state", purpose: "State — matches the HUD MTSP income-limit table." },
  { field: "zip", purpose: "ZIP code — public location data." },
  { field: "total_units", purpose: "Published total units — public HUD field." },
  { field: "low_income_units", purpose: "Published income-restricted units — public HUD field." },
  { field: "bedroom_mix", purpose: "Published bedroom mix — helps renter self-filter by size." },
  { field: "year_placed_in_service", purpose: "Public HUD field — building age context." },
  { field: "availability", purpose: "Always 'unknown' unless the property publishes a live vacancy feed. We never predict it." },
];
